// <auto-generated />
namespace RailwayReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TrainTableUpdated2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainTableUpdated2));
        
        string IMigrationMetadata.Id
        {
            get { return "202408021616265_Train Table Updated 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
