// <auto-generated />
namespace RailwayReservationSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class TrainTableautogenrationofkeyvaluestopped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrainTableautogenrationofkeyvaluestopped));
        
        string IMigrationMetadata.Id
        {
            get { return "202408032327067_Train Table auto genration of key value stopped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
